// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace WebApi.Models
{
    public partial class myDemoDBContext : DbContext
    {
        public myDemoDBContext()
        {
        }

        public myDemoDBContext(DbContextOptions<myDemoDBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Product> Product { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Product>(entity =>
            {
                entity.HasKey(e => e.商品id)
                    .HasName("PK__商品資料更新01__95B1B1E7C3A50CF0");

                entity.Property(e => e.商品id)
                    .ValueGeneratedNever()
                    .HasColumnName("商品ID");

                entity.Property(e => e.商品份數口味)
                    .HasMaxLength(50)
                    .HasColumnName("商品份數/口味");

                entity.Property(e => e.商品名稱).HasMaxLength(50);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}