// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApi.Models
{
    public partial class Product
    {
        public int 商品id { get; set; }
        public string 商品名稱 { get; set; }
        public string 商品份數口味 { get; set; }
        public int? 商品定價 { get; set; }
    }
}