// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApi.Models
{
    public partial class Schedule
    {
        public Schedule()
        {
            SignUp = new HashSet<SignUp>();
        }

        public DateTime Date { get; set; }
        public int? MemberId { get; set; }
        public int? ProductId { get; set; }
        public string ClassName { get; set; }
        public int? PeopleNumber { get; set; }
        public string Note { get; set; }

        public virtual Member Member { get; set; }
        public virtual Product Product { get; set; }
        public virtual ICollection<SignUp> SignUp { get; set; }
    }
}