// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApi.Models
{
    public partial class SignUp
    {
        public DateTime Date { get; set; }
        public int MemberId { get; set; }
        public bool? IsJoin { get; set; }

        public virtual Schedule DateNavigation { get; set; }
        public virtual Member Member { get; set; }
    }
}