// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace backIndex.Models
{
    public partial class HashTag
    {
        public string ProductName { get; set; }
        public string Specifications { get; set; }
        public string HashTag1 { get; set; }

        public virtual Product Product { get; set; }
    }
}