// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace backIndex.Models
{
    public partial class Member
    {
        public Member()
        {
            Blog = new HashSet<Blog>();
            Order = new HashSet<Order>();
            Schedule = new HashSet<Schedule>();
        }

        public int MemberId { get; set; }
        public string Name { get; set; }
        public string NickName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string Password { get; set; }
        public DateTime? BirthDay { get; set; }

        public virtual ICollection<Blog> Blog { get; set; }
        public virtual ICollection<Order> Order { get; set; }
        public virtual ICollection<Schedule> Schedule { get; set; }
    }
}