// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace backIndex.Models
{
    public partial class Product
    {
        public Product()
        {
            HashTag = new HashSet<HashTag>();
            Order = new HashSet<Order>();
        }

        public string ProductName { get; set; }
        public string Specifications { get; set; }
        public int? Price { get; set; }
        public string ImageName { get; set; }
        public bool? Avalible { get; set; }

        public virtual ICollection<HashTag> HashTag { get; set; }
        public virtual ICollection<Order> Order { get; set; }
    }
}